# -*- coding: utf-8 -*-
"""Pothole_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rnrJfUULjI12uwz8baWOa28fptebE2qC
"""

from google.colab import files
uploaded = files.upload()

import zipfile
import os

with zipfile.ZipFile("images.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/images")


os.listdir("/content/images/archive (1)")

import cv2
import numpy as np
import os

data = []
labels = []


base_path = '/content/images/archive (1)'

for category in ['normal', 'potholes']:
    folder = os.path.join(base_path, category)
    label = 0 if category == 'normal' else 1

    for file in os.listdir(folder):
        img_path = os.path.join(folder, file)
        try:
            img = cv2.imread(img_path)
            img = cv2.resize(img, (128, 128))
            img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            data.append(img.flatten())
            labels.append(label)
        except:
            pass

X = np.array(data)
y = np.array(labels)

print("Dataset loaded successfully!")
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(  X, y, test_size=0.2, random_state=42, stratify=y)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

# SVM
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

svm_model = SVC(kernel='rbf', C=1, gamma='scale')
svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)
svm_acc = accuracy_score(y_test, y_pred_svm)

print(" SVM Accuracy:", round(svm_acc * 100, 2), "%")

# Random Forest
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)
rf_acc = accuracy_score(y_test, y_pred_rf)

print(" Random Forest Accuracy:", round(rf_acc * 100, 2), "%")

#Evaluation metrics
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

print("SVM Classification Report:")
print(classification_report(y_test, y_pred_svm))

print("\nRandom Forest Classification Report:")
print(classification_report(y_test, y_pred_rf))

cm = confusion_matrix(y_test, y_pred_rf)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Random Forest Confusion Matrix")
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

cm = confusion_matrix(y_test, y_pred_svm)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("SVM Confusion Matrix")
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# Model Testing
def predict_image(path, model):
    img = cv2.imread(path)
    img = cv2.resize(img, (128, 128))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    f = img.flatten().reshape(1, -1)
    pred = model.predict(f)
    return "Pothole" if pred[0] == 1 else "Normal Road"

import cv2
from google.colab.patches import cv2_imshow

test_image_path = '/content/Pathole.jpg'
test_image=cv2.imread(test_image_path)
cv2_imshow(test_image)
print(predict_image(test_image_path, rf_model))